import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";



export const metadata: Metadata = {
  title: "Summarizer - AI Powered Note Summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
